### ISSUE TITLE
Please add a .plugin.zsh file

### ISSUE THREAD

**Issue by unixorn** [jnooree/zoxide-zsh-completion#1]
In addition to the current instructions in the readme, please consider add a `zoxide.plugin.zsh` file containing the `fpath=(/path/to/zoxide-zsh-completion/functions $fpath)` needed to load the completions. This will make it compatible with most ZSH frameworks.

See the [ZSH Plugin Standard](https://zdharma-continuum.github.io/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html) for details, but TL;DR - name it `zoxide-completion.plugin.zsh` and most frameworks will automagically find and load the file.

**Comment by jnooree** [comment]
Thanks for suggestion!
